import { Dashboard, BarChartOutlined, Insights } from "@mui/icons-material";

export const LOCATIONS = [
  {
    id: "nationwide",
    name: "Nationwide",
    grouped: false,
    data: null,
  },
  {
    id: "cebu",
    name: "Cebu",
    grouped: true,
    data: [
      "Lapu-lapu",
      "Cordova",
      "Mactan",
      "Lapu-lapu City",
      "Lapu- lapu City",
      "Lapu - lapu City",
      "Cebu",
    ],
  },
  {
    id: "davao",
    name: "Davao",
    grouped: false,
    data: null,
  },
  {
    id: "bohol",
    name: "Bohol",
    grouped: false,
    data: null,
  },
  {
    id: "gensan",
    name: "Gensan",
    grouped: true,
    data: [
      "General Santos",
      "Sultan Kudarat",
      "South Cotabato",
      "Sarangani",
      "Cotabato",
      "Cotabato City",
    ],
  },
  {
    id: "dumaguete",
    name: "Dumaguete",
    grouped: true,
    data: ["Dumaguete", "Negros Oriental", "Siquijor"],
  },
  {
    id: "iloilo",
    name: "Iloilo",
    grouped: true,
    data: [
      "Iloilo",
      "Aklan",
      "Capiz",
      "Antique",
      "Roxas",
      "Kalibo",
      "Guimaras",
    ],
  },
  {
    id: "butuan",
    name: "Butuan",
    grouped: true,
    data: [
      "Butuan",
      "Agusan Del Sur",
      "Agusan del Norte",
      "Surigao del Norte",
      "Surigao del Sur",
    ],
  },
  {
    id: "metro-manila",
    name: "Metro Manila",
    grouped: true,
    data: [
      "Metro Manila",
      "Manila",
      "Bulacan",
      "Cavite",
      "Rizal",
      "Laguna",
      "Camarines Sur",
      "Batangas",
      "Ilocos Sur",
      "Ilocos Norte",
      "Camarines Norte",
      "Albay",
      "Tarlac",
      "Pampanga",
      "Pangasinan",
      "Sorsogon",
      "Ifugao",
    ],
  },
  {
    id: "bacolod",
    name: "Bacolod",
    grouped: true,
    data: ["Bacolod", "Negros Occidental"],
  },
  {
    id: "cagayan",
    name: "Cagayan",
    grouped: true,
    data: [
      "Misamis Oriental",
      "Bukidnon",
      "Lanao del Norte",
      "Zamboanga del Sur",
      "Zamboanga del Norte",
      "Misamis Occidental",
      "Lanao del Sur",
    ],
  },
  {
    id: "iligan",
    name: "Iligan",
    grouped: false,
    data: null,
  },
  {
    id: "leyte",
    name: "Leyte",
    grouped: true,
    data: [
      "Leyte",
      "Samar",
      "Tacloban",
      "Southern Leyte",
      "Ormoc",
      "Northern Samar",
    ],
  },
  {
    id: "palawan",
    name: "Palawan",
    grouped: false,
    data: null,
  },
  {
    id: "pampanga",
    name: "Pampanga",
    grouped: false,
    data: null,
  },
];

export const appRoutes = [
  {
    path: "/",
    name: "Overview",
    icon: Dashboard,
  },
  {
    path: "/reports",
    name: "Reports",
    icon: BarChartOutlined,
  },
  {
    path: "/pinning-tracker",
    name: "Pinning Tracker",
    icon: Insights,
  },
];
